# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS   := non_priviledged_process priviledged_process
BPF_TARGETS    := xdpsock_kern

LDLIBS += -lpthread
LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
